// cdn explorer — a thin Hono Worker that lists the R2 bucket behind a password.
//
// Runs on Cloudflare Workers. R2 is reached through the `BUCKET` binding, the
// password/secrets come from `env` (wrangler secrets / .dev.vars), and the static
// UI is read from the `ASSETS` binding. No Bun, no S3 client, no `passage`. The
// `share` CLI (bin/share) writes through POST /api/upload here, not S3 — so the
// CDN owns every R2 write, and the CLI's only credential is the upload bearer.
//
//   bun run dev      # wrangler dev — local R2 sim + .dev.vars
//   bun run deploy   # wrangler deploy
//
// `Env` is generated by `wrangler types` (worker-configuration.d.ts) — never
// hand-written, so it always matches wrangler.jsonc.

import { Hono } from "hono";
import { deleteCookie, getSignedCookie, setSignedCookie } from "hono/cookie";

import { folderPage } from "./folder.ts";
import { DOMAIN, mimeFor, publicUrl } from "./lib/cdn.ts";
import {
  createFolder,
  listFolder,
  move,
  remove,
  rename,
  setPermanent,
  sweep,
  tree,
} from "./storage.ts";

const COOKIE = "cdn_session";
const errMsg = (e: unknown) => (e instanceof Error ? e.message : String(e));

// Evict keys from the edge cache after a write, so an overwritten key serves the
// new bytes immediately (the "?v2 footgun"). Cache entries are keyed by the full
// request URL, so purge under the origin the mutation arrived on (in prod that's
// cdn.ramonfabrega.com — the same host GETs hit). The Cache API is per-POP: this
// clears the POP that handled the mutation — the one you're about to re-fetch
// from — while other POPs age out via s-maxage (≤1h, see the GET handler). Capped
// so a huge folder delete can't blow the per-request subrequest budget; beyond
// the cap we just let s-maxage do its job.
const purgeEdge = (origin: string, keys: string[]) =>
  Promise.all(keys.slice(0, 100).map((k) => caches.default.delete(new Request(`${origin}/${k}`))));
// Only the explorer itself is gated; object paths (the CDN) + auth pages are public.
const isAdminPath = (path: string) => path === "/" || path.startsWith("/api/");

// Secrets live on env (per-request), not a module global. Auth fails CLOSED:
// with no CDN_PASSWORD configured, every login is rejected — never a baked-in
// default. Local dev supplies CDN_PASSWORD + CDN_SESSION_SECRET via .dev.vars.
const sessionSecret = (env: Env) =>
  env.CDN_SESSION_SECRET || `${env.CDN_PASSWORD ?? ""}::cdn-explorer-session`;

// The `share` CLI can't run the cookie login flow, so uploads accept a bearer
// token instead. Scoped to POST /api/upload only (see the gate) and fails CLOSED
// — no CDN_UPLOAD_TOKEN configured ⇒ every bearer is rejected. Distinct from
// CDN_PASSWORD: a high-entropy machine token that can't reach the destructive APIs.
const bearerOk = (env: Env, auth?: string) =>
  !!env.CDN_UPLOAD_TOKEN && auth === `Bearer ${env.CDN_UPLOAD_TOKEN}`;

const app = new Hono<{ Bindings: Env }>();

// Default to no-store (the explorer/API must never cache — fixes "reload shows
// stale UI"). Object serving opts back in by setting its own Cache-Control, which
// we leave untouched.
app.use("*", async (c, next) => {
  await next();
  if (!c.res.headers.has("cache-control")) c.header("Cache-Control", "no-store");
});

// ── auth gate — protects only the explorer (/ and /api/*). Object serving (the
// CDN) and the auth pages stay public. ───────────────────────────────────────
app.use("*", async (c, next) => {
  const path = new URL(c.req.url).pathname;
  if (!isAdminPath(path)) return next();
  // Uploads may authenticate with the bearer token (the `share` CLI); everything
  // else — the explorer + destructive APIs — requires the signed session cookie.
  if (path === "/api/upload" && bearerOk(c.env, c.req.header("authorization"))) return next();
  const ok = await getSignedCookie(c, sessionSecret(c.env), COOKIE);
  if (ok !== "ok") {
    if (path.startsWith("/api/")) return c.json({ error: "unauthorized" }, 401);
    return c.redirect("/login");
  }
  return next();
});

app.get("/health", (c) => c.text("ok"));

// ── login / logout ──────────────────────────────────────────────────────────
app.get("/login", (c) => c.html(loginPage()));

app.post("/login", async (c) => {
  const body = await c.req.parseBody();
  const pw = c.env.CDN_PASSWORD;
  if (pw && body.password === pw) {
    await setSignedCookie(c, COOKIE, "ok", sessionSecret(c.env), {
      httpOnly: true,
      sameSite: "Lax",
      path: "/",
      maxAge: 60 * 60 * 24 * 30, // 30 days
    });
    return c.redirect("/");
  }
  return c.html(loginPage("Wrong password."), 401);
});

app.get("/logout", (c) => {
  deleteCookie(c, COOKIE, { path: "/" });
  return c.redirect("/login");
});

// ── listing API ───────────────────────────────────────────────────────────
// Full enriched object list; the client builds the folder tree from the keys.
app.get("/api/tree", async (c) => {
  try {
    return c.json({ domain: DOMAIN, objects: await tree(c.env.BUCKET) });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 500);
  }
});

// ── mutations (all destructive to public URLs — client confirms first) ──────
app.post("/api/folder", async (c) => {
  try {
    const { prefix = "", name } = await c.req.json();
    const key = await createFolder(c.env.BUCKET, prefix, name);
    return c.json({ ok: true, key });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// move accepts a single `from` or a batch `keys: string[]`, all into folder `to`.
app.post("/api/move", async (c) => {
  try {
    const { from, keys, to = "" } = await c.req.json();
    const list: string[] = Array.isArray(keys) ? keys : from ? [from] : [];
    if (!list.length) throw new Error("missing 'from' or 'keys'");
    const results: { key: string; ok: boolean; error?: string }[] = [];
    const purge: string[] = [];
    let moved = 0;
    for (const k of list) {
      try {
        const m = await move(c.env.BUCKET, k, to);
        moved += m.count;
        purge.push(...m.purge);
        results.push({ key: k, ok: true });
      } catch (e) {
        results.push({ key: k, ok: false, error: errMsg(e) });
      }
    }
    await purgeEdge(new URL(c.req.url).origin, purge);
    return c.json({ ok: results.every((r) => r.ok), moved, results });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

app.post("/api/rename", async (c) => {
  try {
    const { key, name } = await c.req.json();
    if (!key) throw new Error("missing 'key'");
    const m = await rename(c.env.BUCKET, key, name);
    await purgeEdge(new URL(c.req.url).origin, m.purge);
    return c.json({ ok: true, renamed: m.count });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// delete accepts a single `key` or a batch `keys: string[]`.
app.post("/api/delete", async (c) => {
  try {
    const { key, keys } = await c.req.json();
    const list: string[] = Array.isArray(keys) ? keys : key ? [key] : [];
    if (!list.length) throw new Error("missing 'key' or 'keys'");
    const results: { key: string; ok: boolean; error?: string }[] = [];
    const purge: string[] = [];
    let deleted = 0;
    for (const k of list) {
      try {
        const m = await remove(c.env.BUCKET, k);
        deleted += m.count;
        purge.push(...m.purge);
        results.push({ key: k, ok: true });
      } catch (e) {
        results.push({ key: k, ok: false, error: errMsg(e) });
      }
    }
    await purgeEdge(new URL(c.req.url).origin, purge);
    return c.json({ ok: results.every((r) => r.ok), deleted, results });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// ── upload ───────────────────────────────────────────────────────────────────
// Authenticated write — the `share` CLI (bearer) and the explorer's drag-drop
// (cookie) both POST here, replacing the old S3-from-the-CLI path. The client
// chooses the key (`?key=`); key-gen stays client-side. The body is the raw file
// bytes, streamed straight to R2 — no buffering, so large videos are fine. The
// stored content-type comes from the key's extension (our "classify by extension"
// rule — the client doesn't get to set it). Overwrites, like the old S3 write did.
// `?permanent=1` exempts the object from the expiry sweep; when the param is
// absent, an overwrite KEEPS the existing flag — a release script that forgets
// --permanent must not silently re-arm the 30d expiry. Pass permanent=0 to clear.
app.post("/api/upload", async (c) => {
  try {
    const key = (c.req.query("key") ?? "").replace(/^\/+/, "");
    if (
      !key ||
      key.endsWith("/") ||
      key.endsWith("/.keep") ||
      key === ".keep" ||
      key.includes("..")
    )
      throw new Error("invalid or missing 'key'");
    const q = c.req.query("permanent");
    const permanent =
      q === undefined
        ? (await c.env.BUCKET.head(key))?.customMetadata?.permanent === "1"
        : ["1", "true"].includes(q);
    await c.env.BUCKET.put(key, c.req.raw.body, {
      httpMetadata: { contentType: mimeFor(key) },
      customMetadata: permanent ? { permanent: "1" } : undefined,
    });
    await purgeEdge(new URL(c.req.url).origin, [key]); // an overwritten key must serve the new bytes immediately
    return c.json({ ok: true, key, url: publicUrl(key), permanent });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// Flip the `permanent` flag on an existing object (cookie-gated, like the other
// mutations — the upload bearer can only set it at upload time).
app.post("/api/permanent", async (c) => {
  try {
    const { key, permanent } = await c.req.json();
    if (!key) throw new Error("missing 'key'");
    await setPermanent(c.env.BUCKET, key, !!permanent);
    return c.json({ ok: true, key, permanent: !!permanent });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// ── explorer UI ─────────────────────────────────────────────────────────────
// Serve the whole explorer as ONE self-contained document: css + js are inlined
// into index.html so the first (and only) paint is fully styled and interactive.
// No render-blocking subrequest ⇒ no flash of unstyled content, even on GPRS.
// The three files live in public/ (the ASSETS binding); we read + compose them
// here. assets.run_worker_first=true keeps them behind the auth gate.
function inlineOnce(html: string, marker: string, replacement: string): string {
  if (!html.includes(marker)) throw new Error(`inline marker missing: ${marker}`);
  return html.replace(marker, () => replacement); // fn replacer: css/js contain `$`
}
// hostname is ignored by the ASSETS binding — only the pathname matters.
const readAsset = (env: Env, path: string) =>
  env.ASSETS.fetch(new Request(`https://assets.local${path}`)).then((r) => r.text());

app.get("/", async (c) => {
  const [html, css, js] = await Promise.all([
    readAsset(c.env, "/index.html"),
    readAsset(c.env, "/styles.css"),
    readAsset(c.env, "/app.js"),
  ]);
  const page = inlineOnce(
    inlineOnce(html, '<link rel="stylesheet" href="/styles.css">', `<style>${css}</style>`),
    '<script type="module" src="/app.js"></script>',
    `<script type="module">${js}</script>`
  );
  return c.html(page);
});

// Parse a Range header into absolute byte offsets, given the object size.
function parseRange(header: string, size: number): { start: number; end: number } {
  const m = /bytes=(\d*)-(\d*)/.exec(header);
  const a = m?.[1] ? Number(m[1]) : Number.NaN;
  const b = m?.[2] ? Number(m[2]) : Number.NaN;
  if (Number.isNaN(a)) return { start: Math.max(0, size - b), end: size - 1 }; // bytes=-N (suffix)
  return { start: a, end: Number.isNaN(b) ? size - 1 : Math.min(b, size - 1) };
}

// ── public object serving (the CDN) ──────────────────────────────────────────
// Any path that isn't an explorer route is an R2 key. Served publicly (this is
// what `share` links hit), with range + conditional support and an edge cache.
// Explicit routes above win, so reserved words (/login, /api, …) never shadow a key.
app.on(["GET", "HEAD"], "/*", async (c) => {
  const key = decodeURIComponent(new URL(c.req.url).pathname.slice(1));
  if (!key || key.endsWith("/.keep") || key === ".keep") {
    return c.notFound();
  }

  // Folder share links: …/golf-sim/sfx-family/ renders a public read-only
  // listing of that prefix — the "natural" link for a set of uploads. Public by
  // design: every object under it is public anyway; this only reveals sibling
  // keys within a prefix someone already has. Not edge-cached (mutations can't
  // purge a folder page), just a short client max-age.
  if (key.endsWith("/")) {
    const { files, folders } = await listFolder(c.env.BUCKET, key);
    // an empty folder still "exists" while its .keep marker does
    if (!files.length && !folders.length && !(await c.env.BUCKET.head(`${key}.keep`))) {
      return c.notFound();
    }
    const body = c.req.method === "HEAD" ? null : folderPage(key, files, folders);
    return c.html(body ?? "", 200, { "cache-control": "public, max-age=300" });
  }

  const cache = caches.default;
  const wantsRange = c.req.raw.headers.has("range");
  const cacheable = c.req.method === "GET" && !wantsRange;
  if (cacheable) {
    const hit = await cache.match(c.req.raw);
    if (hit) return hit;
  }

  // R2 parses Range + conditional (If-None-Match, …) straight from the headers.
  const obj = await c.env.BUCKET.get(key, {
    range: wantsRange ? c.req.raw.headers : undefined,
    onlyIf: c.req.raw.headers,
  });
  if (!obj) {
    // …/golf-sim/sfx-family (no slash, no such object) → the canonical folder
    // URL when the prefix has content. One cheap probe per would-be 404.
    const probe = await c.env.BUCKET.list({ prefix: `${key}/`, limit: 1 });
    if (probe.objects.length) return c.redirect(`${new URL(c.req.url).pathname}/`, 301);
    return c.notFound();
  }

  const headers = new Headers();
  obj.writeHttpMetadata(headers); // content-type & friends from stored metadata
  headers.set("etag", obj.httpEtag);
  headers.set("accept-ranges", "bytes");
  // Freshness policy. `.xml` keys are mutable pointers (mux's Sparkle appcast is
  // overwritten in place every release) — clients must re-check within minutes,
  // so they get a short max-age everywhere. Everything else caches a day in the
  // client but only an hour at any single edge POP (s-maxage): purge-on-write
  // only clears the POP that handled the write, so s-maxage bounds how long an
  // overwritten key can serve stale bytes from every other POP.
  headers.set(
    "cache-control",
    key.toLowerCase().endsWith(".xml")
      ? "public, max-age=300"
      : "public, max-age=86400, s-maxage=3600"
  );

  if (!("body" in obj)) return new Response(null, { status: 304, headers }); // onlyIf matched
  const body = c.req.method === "HEAD" ? null : obj.body;

  if (wantsRange && obj.range) {
    const { start, end } = parseRange(c.req.raw.headers.get("range") ?? "", obj.size);
    headers.set("content-range", `bytes ${start}-${end}/${obj.size}`);
    headers.set("content-length", String(end - start + 1));
    return new Response(body, { status: 206, headers });
  }

  headers.set("content-length", String(obj.size));
  const res = new Response(body, { status: 200, headers });
  if (cacheable) c.executionCtx.waitUntil(cache.put(c.req.raw, res.clone()));
  return res;
});

function loginPage(error?: string): string {
  return `<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>cdn · sign in</title>
<style>
  /* same OKLCH palette as the explorer (styles.css), light + dark via light-dark() */
  :root{
    color-scheme:light dark;
    --bg:light-dark(oklch(97.5% .004 265),oklch(15% .008 265));
    --card:light-dark(oklch(99.5% .002 265),oklch(19% .009 265));
    --line:light-dark(oklch(91% .01 265),oklch(26% .013 265));
    --line2:light-dark(oklch(86% .013 265),oklch(31% .016 265));
    --ink:light-dark(oklch(25% .02 265),oklch(94% .008 265));
    --dim:light-dark(oklch(45% .022 265),oklch(71% .023 265));
    --faint:light-dark(oklch(60% .018 265),oklch(52% .022 265));
    --accent:oklch(58% .19 265);
    --on-accent:oklch(100% 0 0);
    --red:oklch(62% .2 20);
    --shadow:light-dark(oklch(50% .03 265/.15),oklch(0% 0 0/.5));
  }
  *{box-sizing:border-box}
  body{margin:0;min-height:100dvh;display:grid;place-items:center;
    font:15px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif;
    background:var(--bg);color:var(--ink)}
  form{width:min(92vw,320px);display:flex;flex-direction:column;gap:14px;
    padding:28px;border:1px solid var(--line2);border-radius:16px;
    background:var(--card);box-shadow:0 16px 48px var(--shadow)}
  h1{margin:0;font-size:15px;letter-spacing:.04em;color:var(--dim);font-weight:600}
  h1 b{color:var(--ink);font-weight:600}
  input{padding:11px 13px;border:1px solid var(--line);border-radius:10px;
    background:var(--bg);color:var(--ink);font-size:15px;outline:none}
  input::placeholder{color:var(--faint)}
  input:focus{border-color:var(--accent)}
  button{padding:11px;border:0;border-radius:10px;background:var(--accent);
    color:var(--on-accent);font-size:15px;font-weight:600;cursor:pointer;
    transition:filter .15s}
  button:hover{filter:brightness(1.08)}
  .err{color:var(--red);font-size:13px;margin:0}
</style></head><body>
<form method="post" action="/login">
  <h1>🔒 <b>cdn</b>.ramonfabrega.com</h1>
  ${error ? `<p class="err">${error}</p>` : ""}
  <input type="password" name="password" placeholder="password" autofocus required>
  <button type="submit">Enter</button>
</form></body></html>`;
}

export default {
  fetch: app.fetch,
  // Daily expiry sweep — replaces the bucket's blanket 30d R2 lifecycle rule,
  // which couldn't exempt `permanent` objects. Scheduled by wrangler.jsonc
  // `triggers.crons`.
  scheduled: (_event, env, ctx) => ctx.waitUntil(sweep(env.BUCKET)),
} satisfies ExportedHandler<Env>;
