// cdn explorer — a thin Hono Worker that lists the R2 bucket behind a password.
//
// Runs on Cloudflare Workers. R2 is reached through the `BUCKET` binding, the
// password/secrets come from `env` (wrangler secrets / .dev.vars), and the static
// UI is read from the `ASSETS` binding. No Bun, no S3 client, no `passage`. The
// `share` CLI (bin/share) writes through POST /api/upload here, not S3 — so the
// CDN owns every R2 write, and the CLI's only credential is the upload bearer.
//
//   bun run dev      # wrangler dev — local R2 sim + .dev.vars
//   bun run deploy   # wrangler deploy
//
// `Env` is generated by `wrangler types` (worker-configuration.d.ts) — never
// hand-written, so it always matches wrangler.jsonc.

import { Hono } from "hono";
import { deleteCookie, getSignedCookie, setSignedCookie } from "hono/cookie";
import { stream } from "hono/streaming";
import { ImageResponse } from "takumi-js/response";

import { CARD_FONTS, folderCard } from "./card.ts";
import { folderPage } from "./folder.tsx";
import { mimeFor, publicUrl } from "./lib/cdn.ts";
import { brand, escapeHtml } from "./lib/ui.ts";
import { loginPage } from "./login.tsx";
import {
  createFolder,
  listFolder,
  listSubtree,
  move,
  remove,
  rename,
  setPermanent,
  sweep,
  tree,
} from "./storage.ts";

const COOKIE = "cdn_session";
const errMsg = (e: unknown) => (e instanceof Error ? e.message : String(e));

// ── cache purge ──────────────────────────────────────────────────────────────
// Evict keys from the edge cache after a write, so an overwritten key serves the
// new bytes immediately (the "?v2 footgun"). Two mechanisms, because neither is
// sufficient alone:
//
//   • `caches.default.delete()` — free and immediate, but the Cache API is
//     per-POP: it clears ONLY the data center this Worker ran in.
//   • the zone purge API — global (every POP), a couple of seconds, and needs a
//     credential: CDN_PURGE_TOKEN, a Zone.Cache Purge token for CDN_ZONE_ID.
//
// The local delete alone was the whole policy until now: "the writing POP is
// fresh, everyone else ages out via s-maxage (≤1h)". Fine for a screenshot link,
// wrong for a release feed — an OTA client on another continent could read an
// hour-old `appcast.xml`, and worse, pair a FRESH appcast with the STALE bytes of
// a stable `*-latest.zip` key, which fails Sparkle's signature check rather than
// merely looking old. The zone purge makes "an overwrite is visible immediately"
// true everywhere instead of only where you happened to upload from.
//
// The zone purge always names the PUBLIC origin (CDN_PUBLIC_ORIGIN), never the
// request's: a preview version shares production's bindings, so a write from a
// *.workers.dev preview mutates the live bucket and must invalidate the live
// domain. The request origin is purged locally too, so `wrangler dev` and
// previews re-read their own writes. With no CDN_PUBLIC_ORIGIN set — the
// template's default, before an instance has a domain — the request origin IS
// the public one and the distinction collapses.
//
// Capped so a huge folder delete can't blow the per-request subrequest budget;
// beyond the cap we let s-maxage do its job, as before.
const PURGE_CAP = 100;
const PURGE_BATCH = 30; // Cloudflare's purge-by-url limit per API call

// CDN_ZONE_ID and CDN_PUBLIC_ORIGIN are OPTIONAL vars an INSTANCE adds to its
// own wrangler.jsonc once it owns a custom domain. The template ships without
// them on purpose — a fresh Deploy to Cloudflare has no zone and no domain yet,
// and prompting for two values nobody can answer is not a one-click deploy — so
// they are absent from the generated Env and read as what they are: config that
// may or may not be there. Absent ⇒ the purge is local-POP only, never an error.
const optionalVar = (env: Env, key: string): string | undefined => {
  const value: unknown = Reflect.get(env, key);
  return typeof value === "string" && value ? value : undefined;
};

const purgeZone = async (env: Env, urls: string[]) => {
  // No token or no zone configured (tests, `wrangler dev`, a fresh deploy) ⇒
  // local-only purge, i.e. exactly the pre-#49 behavior. Never fatal.
  const zone = optionalVar(env, "CDN_ZONE_ID");
  if (!env.CDN_PURGE_TOKEN || !zone) return;
  for (let i = 0; i < urls.length; i += PURGE_BATCH) {
    const files = urls.slice(i, i + PURGE_BATCH);
    const res = await fetch(`https://api.cloudflare.com/client/v4/zones/${zone}/purge_cache`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.CDN_PURGE_TOKEN}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({ files }),
    });
    // A failed purge must NOT fail the write: the bytes are already in R2, and
    // telling `share` the upload failed would be a lie that makes release scripts
    // retry a write that succeeded. Log it instead (observability is on) — a
    // silent purge failure is precisely how this class of staleness bug hides.
    if (!res.ok) {
      console.error(
        `zone purge failed (${res.status}) for ${files.length} url(s): ${(await res.text().catch(() => "")).slice(0, 300)}`
      );
    }
  }
};

const purgeEdge = async (env: Env, origin: string, keys: string[]) => {
  const capped = keys.slice(0, PURGE_CAP);
  // Cache entries are keyed by the full request URL; publicUrl builds exactly the
  // form the world fetches (and `share` prints), so the delete matches the entry.
  await Promise.all(capped.map((k) => caches.default.delete(new Request(publicUrl(origin, k)))));
  await purgeZone(
    env,
    capped.map((k) => publicUrl(optionalVar(env, "CDN_PUBLIC_ORIGIN") ?? origin, k))
  );
};
// Only the explorer itself is gated; object paths (the CDN) + auth pages are public.
const isAdminPath = (path: string) => path === "/" || path.startsWith("/api/");

// Secrets live on env (per-request), not a module global. Auth fails CLOSED:
// with no CDN_PASSWORD configured, every login is rejected — never a baked-in
// default. Local dev supplies CDN_PASSWORD + CDN_SESSION_SECRET via .dev.vars.
const sessionSecret = (env: Env) =>
  env.CDN_SESSION_SECRET || `${env.CDN_PASSWORD ?? ""}::cdn-explorer-session`;

// The `share` CLI can't run the cookie login flow, so uploads accept a bearer
// token instead. Scoped to POST /api/upload only (see the gate) and fails CLOSED
// — no CDN_UPLOAD_TOKEN configured ⇒ every bearer is rejected. Distinct from
// CDN_PASSWORD: a high-entropy machine token that can't reach the destructive APIs.
const bearerOk = (env: Env, auth?: string) =>
  !!env.CDN_UPLOAD_TOKEN && auth === `Bearer ${env.CDN_UPLOAD_TOKEN}`;

// The routes the upload bearer reaches, and the whole of its authority. Kept as
// a set rather than a prefix so widening it is a deliberate edit: everything
// under /api/ that isn't listed here needs the cookie.
const BEARER_PATHS = new Set(["/api/upload", "/api/auth"]);

const app = new Hono<{ Bindings: Env }>();

// Default to no-store (the explorer/API must never cache — fixes "reload shows
// stale UI"). Object serving opts back in by setting its own Cache-Control, which
// we leave untouched.
app.use("*", async (c, next) => {
  await next();
  if (!c.res.headers.has("cache-control")) c.header("Cache-Control", "no-store");
});

// ── auth gate — protects only the explorer (/ and /api/*). Object serving (the
// CDN) and the auth pages stay public. ───────────────────────────────────────
app.use("*", async (c, next) => {
  const path = new URL(c.req.url).pathname;
  if (!isAdminPath(path)) return next();
  // Two routes take the bearer: the write itself, and the no-op that exists so a
  // client can find out whether its bearer works without writing. Everything
  // else — the explorer + destructive APIs — requires the signed session cookie.
  if (BEARER_PATHS.has(path) && bearerOk(c.env, c.req.header("authorization"))) return next();
  const ok = await getSignedCookie(c, sessionSecret(c.env), COOKIE);
  if (ok !== "ok") {
    if (path.startsWith("/api/")) return c.json({ error: "unauthorized" }, 401);
    return c.redirect("/login");
  }
  return next();
});

app.get("/health", (c) => c.text("ok"));

// ── auth check ───────────────────────────────────────────────────────────────
// A cheap authenticated no-op, so a client can find out whether its credential
// works without writing anything. `cdn auth login` verifies a token before it
// puts it on disk, and the only alternative was to upload a file — a side effect
// nobody asked for while logging in, and one that leaves litter in the bucket
// when the token turns out to be wrong.
//
// The gate above does the rejecting: reaching this handler already means a valid
// bearer or a valid session, so the body is just the good news. 204, because
// there is nothing to say — the status IS the answer.
app.get("/api/auth", (c) => c.body(null, 204));

// ── login / logout ──────────────────────────────────────────────────────────
app.get("/login", (c) => c.html(loginPage(new URL(c.req.url).host)));

app.post("/login", async (c) => {
  const body = await c.req.parseBody();
  const pw = c.env.CDN_PASSWORD;
  if (pw && body.password === pw) {
    await setSignedCookie(c, COOKIE, "ok", sessionSecret(c.env), {
      httpOnly: true,
      sameSite: "Lax",
      path: "/",
      maxAge: 60 * 60 * 24 * 30, // 30 days
    });
    return c.redirect("/");
  }
  return c.html(loginPage(new URL(c.req.url).host, "Wrong password."), 401);
});

app.get("/logout", (c) => {
  deleteCookie(c, COOKIE, { path: "/" });
  return c.redirect("/login");
});

// ── listing API ───────────────────────────────────────────────────────────
// Full enriched object list; the client builds the folder tree from the keys.
// Entry urls carry the REQUEST origin (custom domain, preview build, dev) — the
// explorer's copy-link must match the host you're on, so testing a preview never
// hands out prod links. No `domain` field: app.js uses location.host, same thing.
app.get("/api/tree", async (c) => {
  try {
    return c.json({ objects: await tree(c.env.BUCKET, new URL(c.req.url).origin) });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 500);
  }
});

// ── mutations (all destructive to public URLs — client confirms first) ──────
app.post("/api/folder", async (c) => {
  try {
    const { prefix = "", name } = await c.req.json();
    const key = await createFolder(c.env.BUCKET, prefix, name);
    return c.json({ ok: true, key });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// move accepts a single `from` or a batch `keys: string[]`, all into folder `to`.
app.post("/api/move", async (c) => {
  try {
    const { from, keys, to = "" } = await c.req.json();
    const list: string[] = Array.isArray(keys) ? keys : from ? [from] : [];
    if (!list.length) throw new Error("missing 'from' or 'keys'");
    const results: { key: string; ok: boolean; error?: string }[] = [];
    const purge: string[] = [];
    let moved = 0;
    for (const k of list) {
      try {
        const m = await move(c.env.BUCKET, k, to);
        moved += m.count;
        purge.push(...m.purge);
        results.push({ key: k, ok: true });
      } catch (e) {
        results.push({ key: k, ok: false, error: errMsg(e) });
      }
    }
    await purgeEdge(c.env, new URL(c.req.url).origin, purge);
    return c.json({ ok: results.every((r) => r.ok), moved, results });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

app.post("/api/rename", async (c) => {
  try {
    const { key, name } = await c.req.json();
    if (!key) throw new Error("missing 'key'");
    const m = await rename(c.env.BUCKET, key, name);
    await purgeEdge(c.env, new URL(c.req.url).origin, m.purge);
    return c.json({ ok: true, renamed: m.count });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// delete accepts a single `key` or a batch `keys: string[]`.
app.post("/api/delete", async (c) => {
  try {
    const { key, keys } = await c.req.json();
    const list: string[] = Array.isArray(keys) ? keys : key ? [key] : [];
    if (!list.length) throw new Error("missing 'key' or 'keys'");
    const results: { key: string; ok: boolean; error?: string }[] = [];
    const purge: string[] = [];
    let deleted = 0;
    for (const k of list) {
      try {
        const m = await remove(c.env.BUCKET, k);
        deleted += m.count;
        purge.push(...m.purge);
        results.push({ key: k, ok: true });
      } catch (e) {
        results.push({ key: k, ok: false, error: errMsg(e) });
      }
    }
    await purgeEdge(c.env, new URL(c.req.url).origin, purge);
    return c.json({ ok: results.every((r) => r.ok), deleted, results });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// ── upload ───────────────────────────────────────────────────────────────────
// Authenticated write — the `share` CLI (bearer) and the explorer's drag-drop
// (cookie) both POST here, replacing the old S3-from-the-CLI path. The client
// chooses the key (`?key=`); key-gen stays client-side. The body is the raw file
// bytes, streamed straight to R2 — no buffering, so large videos are fine. The
// stored content-type comes from the key's extension (our "classify by extension"
// rule — the client doesn't get to set it). Overwrites, like the old S3 write did.
// `?permanent=1` exempts the object from the expiry sweep; when the param is
// absent, an overwrite KEEPS the existing flag — a release script that forgets
// --permanent must not silently re-arm the 30d expiry. Pass permanent=0 to clear.
app.post("/api/upload", async (c) => {
  try {
    const key = (c.req.query("key") ?? "").replace(/^\/+/, "");
    if (
      !key ||
      key.endsWith("/") ||
      key.endsWith("/.keep") ||
      key === ".keep" ||
      key.includes("..")
    )
      throw new Error("invalid or missing 'key'");
    const q = c.req.query("permanent");
    const permanent =
      q === undefined
        ? (await c.env.BUCKET.head(key))?.customMetadata?.permanent === "1"
        : ["1", "true"].includes(q);
    await c.env.BUCKET.put(key, c.req.raw.body, {
      httpMetadata: { contentType: mimeFor(key) },
      customMetadata: permanent ? { permanent: "1" } : undefined,
    });
    const origin = new URL(c.req.url).origin;
    await purgeEdge(c.env, origin, [key]); // an overwritten key must serve the new bytes immediately
    return c.json({ ok: true, key, url: publicUrl(origin, key), permanent });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// Flip the `permanent` flag on an existing object (cookie-gated, like the other
// mutations — the upload bearer can only set it at upload time).
app.post("/api/permanent", async (c) => {
  try {
    const { key, permanent } = await c.req.json();
    if (!key) throw new Error("missing 'key'");
    await setPermanent(c.env.BUCKET, key, !!permanent);
    return c.json({ ok: true, key, permanent: !!permanent });
  } catch (e) {
    return c.json({ error: errMsg(e) }, 400);
  }
});

// ── explorer UI (streamed shell + embedded data) ──────────────────────────────
// One self-contained document (css + js inlined ⇒ no render-blocking subrequest,
// no FOUC), but STREAMED in two flushes so R2 latency never delays first paint:
//   1. shell + static skeleton (css inlined into <head>) flushes immediately, so
//      the skeleton paints before R2 is even queried.
//   2. once tree() resolves, the file list rides along as window.__tree, followed
//      by the inlined app.js — so app.js renders from embedded data with NO
//      /api/tree round-trip (see init() in app.js).
// The Worker streams only the STATIC skeleton + a data blob; it never renders a
// row, so app.js stays the one and only renderer. assets.run_worker_first=true
// keeps these reads behind the auth gate. hostname is ignored by ASSETS — only
// the pathname matters.
const readAsset = (env: Env, path: string) =>
  env.ASSETS.fetch(new Request(`https://assets.local${path}`)).then((r) => r.text());

// Split index.html at the app.js tag: everything before it (shell + skeleton)
// flushes first; the data blob + inlined app.js stream in after R2 resolves.
const JS_TAG = '<script type="module" src="/app.js"></script>';

// The shell's two brand slots (see public/index.html). Filled from the REQUEST
// host, so the explorer wears the domain you're on — the template ships with
// nobody's domain in it, and a preview build never claims to be production.
const fill = (html: string, slot: string, value: string) => {
  if (!html.includes(slot)) throw new Error(`inline marker missing: ${slot}`);
  return html.replace(slot, () => value);
};

app.get("/", async (c) => {
  const [html, css, js] = await Promise.all([
    readAsset(c.env, "/index.html"),
    readAsset(c.env, "/styles.css"),
    readAsset(c.env, "/app.js"),
  ]);
  const idx = html.indexOf(JS_TAG);
  if (idx === -1) throw new Error(`inline marker missing: ${JS_TAG}`);
  const { name, rest } = brand(new URL(c.req.url).host);
  const shell = fill(
    fill(
      html
        .slice(0, idx)
        .replace('<link rel="stylesheet" href="/styles.css">', () => `<style>${css}</style>`),
      "<!--title-->",
      `${escapeHtml(name)} · files`
    ),
    "<!--brand-->",
    `<b>${escapeHtml(name)}</b><span class="host">${escapeHtml(rest)}</span>`
  );
  const tail = html.slice(idx + JS_TAG.length); // "\n</body>\n</html>\n"

  c.header("content-type", "text/html; charset=utf-8");
  return stream(c, async (s) => {
    await s.write(shell); // shell + skeleton → paints now, before R2 is queried
    const objects = await tree(c.env.BUCKET, new URL(c.req.url).origin);
    const json = JSON.stringify(objects).replace(/</g, "\\u003c"); // safe inside <script>
    await s.write(`<script>window.__tree=${json}</script>`);
    await s.write(`<script type="module">${js}</script>`);
    await s.write(tail);
  });
});

// ── og:image cards ────────────────────────────────────────────────────────────
// /.og/<prefix>.png renders the 1200×630 unfurl card for a folder page (the same
// listFolder data, drawn by takumi's WASM renderer — see src/card.ts). Reserved
// under a dot-prefix à la `.keep`, so it can never shadow a real object key.
// Cached like the folder page itself: short client max-age, no edge cache.
app.get("/.og/*", async (c) => {
  const url = new URL(c.req.url);
  const m = /^\/\.og\/(.+)\.png$/.exec(url.pathname);
  if (!m?.[1]) return c.notFound();
  const prefix = `${decodeURIComponent(m[1])}/`;
  const [{ files, folders }, subtree] = await Promise.all([
    listFolder(c.env.BUCKET, prefix, url.origin),
    listSubtree(c.env.BUCKET, prefix), // full-depth sizes for the sunburst
  ]);
  if (!files.length && !folders.length && !(await c.env.BUCKET.head(`${prefix}.keep`))) {
    return c.notFound();
  }
  return new ImageResponse(folderCard(url.host, prefix, files, folders, subtree), {
    width: 1200,
    height: 630,
    format: "png",
    fonts: CARD_FONTS,
    headers: { "cache-control": "public, max-age=300" },
    // render errors happen after the 200 headers stream out — surface them in logs
    onError: (e) => console.error("card render:", e),
  });
});

// Parse a Range header into absolute byte offsets, given the object size.
function parseRange(header: string, size: number): { start: number; end: number } {
  const m = /bytes=(\d*)-(\d*)/.exec(header);
  const a = m?.[1] ? Number(m[1]) : Number.NaN;
  const b = m?.[2] ? Number(m[2]) : Number.NaN;
  if (Number.isNaN(a)) return { start: Math.max(0, size - b), end: size - 1 }; // bytes=-N (suffix)
  return { start: a, end: Number.isNaN(b) ? size - 1 : Math.min(b, size - 1) };
}

// ── public object serving (the CDN) ──────────────────────────────────────────
// Any path that isn't an explorer route is an R2 key. Served publicly (this is
// what `share` links hit), with range + conditional support and an edge cache.
// Explicit routes above win, so reserved words (/login, /api, …) never shadow a key.
app.on(["GET", "HEAD"], "/*", async (c) => {
  const key = decodeURIComponent(new URL(c.req.url).pathname.slice(1));
  if (!key || key.endsWith("/.keep") || key === ".keep") {
    return c.notFound();
  }

  // Folder share links: …/golf-sim/sfx-family/ renders a public read-only
  // listing of that prefix — the "natural" link for a set of uploads. Public by
  // design: every object under it is public anyway; this only reveals sibling
  // keys within a prefix someone already has. Not edge-cached (mutations can't
  // purge a folder page), just a short client max-age.
  if (key.endsWith("/")) {
    const origin = new URL(c.req.url).origin;
    const { files, folders } = await listFolder(c.env.BUCKET, key, origin);
    // an empty folder still "exists" while its .keep marker does
    if (!files.length && !folders.length && !(await c.env.BUCKET.head(`${key}.keep`))) {
      return c.notFound();
    }
    const body = c.req.method === "HEAD" ? null : folderPage(origin, key, files, folders);
    return c.html(body ?? "", 200, { "cache-control": "public, max-age=300" });
  }

  const cache = caches.default;
  const wantsRange = c.req.raw.headers.has("range");
  const cacheable = c.req.method === "GET" && !wantsRange;
  if (cacheable) {
    const hit = await cache.match(c.req.raw);
    if (hit) return hit;
  }

  // R2 parses Range + conditional (If-None-Match, …) straight from the headers.
  const obj = await c.env.BUCKET.get(key, {
    range: wantsRange ? c.req.raw.headers : undefined,
    onlyIf: c.req.raw.headers,
  });
  if (!obj) {
    // …/golf-sim/sfx-family (no slash, no such object) → the canonical folder
    // URL when the prefix has content. One cheap probe per would-be 404.
    const probe = await c.env.BUCKET.list({ prefix: `${key}/`, limit: 1 });
    if (probe.objects.length) return c.redirect(`${new URL(c.req.url).pathname}/`, 301);
    return c.notFound();
  }

  const headers = new Headers();
  obj.writeHttpMetadata(headers); // content-encoding/disposition/… from stored metadata
  // Content-type is re-derived from the key on every serve rather than read back
  // from storage. The extension is ALREADY the sole source of truth on write (the
  // upload ignores the client's content-type), so for anything we stored this is a
  // no-op — its value is that the table becomes retroactive: adding `; charset=utf-8`
  // fixes every .md/.txt already sitting in the bucket, with no metadata backfill,
  // and the same holds for the next entry we add. It also types objects that got
  // into R2 by some other door (dashboard upload, `wrangler r2 object put`).
  headers.set("content-type", mimeFor(key));
  headers.set("etag", obj.httpEtag);
  headers.set("accept-ranges", "bytes");
  // Freshness policy: every key is overwritable in place (same URL, new bytes),
  // so browsers must never trust a stale copy — max-age=0 makes them revalidate
  // each view (If-None-Match → a cheap 304; the edge answers conditionals even on
  // cache hits). The heavy lifting stays at the edge: s-maxage caches an hour per
  // POP, and purge-on-write clears the POP that handled the write, so an
  // overwrite is visible immediately there and within the hour everywhere else.
  // (This replaced max-age=86400 — a day of browser cache made every overwrite
  // look stale until the client cache-busted; one policy, no .xml special case.)
  headers.set("cache-control", "public, max-age=0, s-maxage=3600");

  if (!("body" in obj)) return new Response(null, { status: 304, headers }); // onlyIf matched
  const body = c.req.method === "HEAD" ? null : obj.body;

  if (wantsRange && obj.range) {
    const { start, end } = parseRange(c.req.raw.headers.get("range") ?? "", obj.size);
    headers.set("content-range", `bytes ${start}-${end}/${obj.size}`);
    headers.set("content-length", String(end - start + 1));
    return new Response(body, { status: 206, headers });
  }

  headers.set("content-length", String(obj.size));
  const res = new Response(body, { status: 200, headers });
  if (cacheable) c.executionCtx.waitUntil(cache.put(c.req.raw, res.clone()));
  return res;
});

export default {
  fetch: app.fetch,
  // Daily expiry sweep — replaces the bucket's blanket 30d R2 lifecycle rule,
  // which couldn't exempt `permanent` objects. Scheduled by wrangler.jsonc
  // `triggers.crons`.
  scheduled: (_event, env, ctx) => ctx.waitUntil(sweep(env.BUCKET)),
} satisfies ExportedHandler<Env>;
